/*
Clase 6 en vídeo | 15/08/2024
Clases (continuación) y manejo de errores
https://www.youtube.com/live/8p6SLAIgwZI?si=MS9o7qIhezx9NTQX&t=902
*/
//* 1. Captura una excepción utilizando try-catch
console.log();
console.log("1. Captura una excepción utilizando try-catch");
console.log();

//* 2. Captura una excepción utilizando try-catch y finally
console.log();
console.log("2. Captura una excepción utilizando try-catch y finally");
console.log();

//* 3. Lanza una excepción genérica
console.log();
console.log("3. Lanza una excepción genérica");
console.log();

//* 4. Crea una excepción personalizada
console.log();
console.log("4. Crea una excepción personalizada");
console.log();

//* 5. Lanza una excepción personalizada
console.log();
console.log("5. Lanza una excepción personalizada");
console.log();

//* 6. Lanza varias excepciones según una lógica definida
console.log();
console.log("6. Lanza varias excepciones según una lógica definida");
console.log();

//* 7. Captura varias excepciones en un mismo try-catch
console.log();
console.log("7. Captura varias excepciones en un mismo try-catch");
console.log();

//* 8. Crea un bucle que intente transformar a float cada valor y capture y muestre los errores
console.log();
console.log("8. Crea un bucle que intente transformar a float cada valor y capture y muestre los errores");
console.log();

//* 9. Crea una función que verifique si un objeto tiene una propiedad específica y lance una excepción personalizada
console.log();
console.log("9. Crea una función que verifique si un objeto tiene una propiedad específica y lance una excepción personalizada");
console.log();

//* 10. Crea una función que realice reintentos en caso de error hasta un máximo de 10
console.log();
console.log("10. Crea una función que realice reintentos en caso de error hasta un máximo de 10");
console.log();
